"""add image_path to bottles and cocktail_recipes

Revision ID: b84e7e3b2040
Revises: d193ad6fd6e3
Create Date: 2026-03-05 08:46:09.802071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84e7e3b2040'
down_revision: Union[str, None] = 'd193ad6fd6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.add_column('cocktail_recipes', sa.Column('image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktail_recipes', 'image_path')
    op.drop_column('bottles', 'image_path')
    # ### end Alembic commands ###
