"""initial schema

Revision ID: d193ad6fd6e3
Revises: 
Create Date: 2026-03-04 19:04:26.969477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd193ad6fd6e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('producer', sa.String(length=300), nullable=True),
    sa.Column('type', sa.Enum('wine', 'spirit', 'liqueur', 'beer', 'other', name='bottletype', native_enum=False), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('grape_or_base', sa.String(length=200), nullable=True),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('sugar_content_g_per_100ml', sa.Float(), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('purchase_price_kr', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('source_shop', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_purchased', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('in_stock', 'consumed', 'gifted', name='bottlestatus', native_enum=False), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('enrichment_status', sa.Enum('pending', 'auto_enriched', 'claude_enriched', 'manual', 'confirmed', name='enrichmentstatus', native_enum=False), nullable=False),
    sa.Column('serving_temp', sa.String(length=50), nullable=True),
    sa.Column('drink_window_start', sa.Date(), nullable=True),
    sa.Column('drink_window_end', sa.Date(), nullable=True),
    sa.Column('awards_scores', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('suggested_pairings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.Enum('shake', 'stir', 'build', 'blend', name='cocktailmethod', native_enum=False), nullable=True),
    sa.Column('glass_type', sa.String(length=100), nullable=True),
    sa.Column('garnish', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'advanced', name='cocktaildifficulty', native_enum=False), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('would_make_again', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('flavor', 'type', 'ingredient', name='tagcategory', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bottle_tags',
    sa.Column('bottle_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bottle_id', 'tag_id')
    )
    op.create_table('pantry_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount_cl', sa.Float(), nullable=True),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.Column('is_pantry_item', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['cocktail_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('bottle_id', sa.Uuid(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('manual', 'scan', 'cocktail', name='shoppingsource', native_enum=False), nullable=False),
    sa.Column('is_bought', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasting_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bottle_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tasted_at', sa.Date(), nullable=False),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('food_pairing', sa.Text(), nullable=True),
    sa.Column('pairing_rating', sa.Integer(), nullable=True),
    sa.Column('would_drink_again', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasting_notes')
    op.drop_table('shopping_list_items')
    op.drop_table('recipe_ingredients')
    op.drop_table('pantry_items')
    op.drop_table('bottle_tags')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('cocktail_recipes')
    op.drop_table('bottles')
    # ### end Alembic commands ###
