"""add cocktail enrichment_status

Revision ID: fdd779bc3ad4
Revises: 03af0af19e14
Create Date: 2026-03-06 09:22:20.681509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd779bc3ad4'
down_revision: Union[str, None] = '03af0af19e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktail_recipes', sa.Column('enrichment_status', sa.Enum('pending', 'auto_enriched', 'claude_enriched', 'manual', 'confirmed', name='enrichmentstatus', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktail_recipes', 'enrichment_status')
    # ### end Alembic commands ###
